### ISSUE TITLE
homework1.ipynb

### ISSUE THREAD

**Issue by ralphpeterson** [tjjlemaire/IntroNE#1]
Hi Theo,

I am running the homework1.ipynb notebook locally and have received the following error. Before troubleshooting too much further on my own, I wanted to double check with you if you had any recommendations. All my imports worked fine.

<img width="505" alt="image" src="https://user-images.githubusercontent.com/4031329/157319354-ea1770c6-3a46-45be-bced-0dd668e9aff1.png">

Best,
Ralph

**Comment by tjjlemaire** [comment]
Hi Ralph,

Thanks for bringing that up.

The error is related to the underlying NEURON simulation package. NEURON basically offers a high-level Python interface but under the hood it is running compiled code to speed up simulations. Hence, the differential equations governing the axon's nodal membrane dynamics (defined in the `MRGnode.mod` file) must be compiled in order to be useable by NEURON.

Here's how to do it:
- If you're on Mac/Linux, just go to the repository's folder and type in the command `nrnivmodl`.
- If you're in Windows, open the folder named `NEURON xxx` (`xxx` being the NEURON version number) located on your Desktop, and run the `mknrndll` executable. In the window that appears, move to the repository's folder and then click `make nrnmech.dll`.

Once the MOD file is compiled, restart the notebook and everything should work normally. 

Let me know if that solves it.

Best,
Theo

**Comment by ralphpeterson** [comment]
Hi Theo, 

All good now, that fixed it! Thanks for the quick response.

-Ralph
