### ISSUE TITLE
Task 1

### ISSUE THREAD

**Issue by ssarafcns** [tjjlemaire/IntroNE#2]
Hi Theo,

Posting here in case this is the medium you'd like us to use over email:

regarding task 1:
The axon length changes when the axon diameter in the simulation object is changed.  Is it okay if we input node separation or axon length into the conduction velocity function as a parameter? The codependence of the axon length and axon diameter is also in Table 1 of the paper.  In addition, I think our results won't exactly replicate the results in figure 8 A, as in the paper's simulations, node diameter and other parameters also change with axon diameter -- is this okay?

**Comment by tjjlemaire** [comment]
Hi Sonica,

You are right, the axon model is set with a fixed number of nodes (51), but the node-to-node distance is dependent on the axon diameter, hence so is the overall axon length. 

In the code base, the axon model is set in such a way that if you change its diameter (using _sim.axon.diameter = ..._), the internal parameters (and the resulting node-to-node distance) will change accordingly. Hence, you should have no problem changing the diameter iteratively and replicating the results of figure 8A.

As for the node-to-node separation, you can access it by extracting the nodes longitudinal coordinates (using _sim.axon.xnodes_), as showcased in the notebook. Since you can access the simulation object from within the function, you should not need to modify its footprint.

Hope this helps!
Theo

**Comment by ssarafcns** [comment]
Hi Theo,

This helps a lot! Thank you!

Sonica
